$params = @{
    version="1.6.1"
    permissions=@{
        admin="infinite.announcements.admin"
        toggle="infinite.announcements.toggle"
    }
    random=$true
    interval=900
    sounds=@{
        message1=@()
    }
    messages=@{}
    "World-messaging"=@{
        world=@{}
    }
    color="&6"
    format="&f[&b&lFun Fact&f] "
    totalMessages=0
}
$messages = @{
    message=[System.Collections.ArrayList]@()
    "centered-messages"=[System.Collections.ArrayList]@()
}
[System.Collections.ArrayList]$funFacts = @()
if (-not (test-path -path ".\config.yml") -or `
         (test-path -path ".\config.yml")) {
    $files = (get-childitem -path ".\Data").Name
    if (-not ($null -eq $files)) {
        new-item -path "$PSScriptRoot\config.yml"
        $files |
        ForEach-Object {
            $content = get-content -path ".\Data\$_"
            $content |
            ForEach-Object {
                $funFacts.add($_)
            }
        }
    }
}
$funFacts | 
ForEach-Object {
    $_ = $parms.format + $params.color + $_
}
$params.totalMessages = $funFacts.count
for ($i = 0; $i -lt $params.totalMessages; $i++) {
    $messages.message.add(@{
        name="message$i"
        "centered-name"="  - message$i`n"
        id=$i
        message=@("  message$($i):`n",
                  "    - `"&8&m------------------------------------------`"`n",
                  "    - `"`"`n",
                  "    - $($parms.format + $params.color + $funFacts[$i])`n",
                  "    - `"`"`n",
                  "    - `"&8&m------------------------------------------`"`n")
    })
}
$document = @{
    start=@('# _____       __ _       _ _          ___                                                              _',
            '#|_   _|     / _(_)     (_) |        / _ \                                                            | |',
            '#  | | _ __ | |_ _ _ __  _| |_ ___  / /_\ \_ __  _ __   ___  _   _ _ __   ___ ___ _ __ ___   ___ _ __ | |_ ___',
            '#  | ||  _ \|  _| |  _ \| | __/ _ \ |  _  |  _ \|  _ \ / _ \| | | |  _ \ / __/ _ \  _   _ \ / _ \  _ \| __/ __|',
            '# _| || | | | | | | | | | | ||  __/ | | | | | | | | | | (_) | |_| | | | | (_|  __/ | | | | |  __/ | | | |_\__ \',
            '# \___/_| |_|_| |_|_| |_|_|\__\___| \_| |_/_| |_|_| |_|\___/ \__,_|_| |_|\___\___|_| |_| |_|\___|_| |_|\__|___/',
            '#',
            '#                               Created by Infinite Plugins, generated by https://github.com/RileyCarney',
            '',
            '# Do not change this unless you know what you are doing')
    defaults=@("version: $($params.version)",
               "permissions:",
               "admin: $($params.permissions.admin)",
               "toggle: $($params.permissions.toggle)",
               "Random: $($params.random)",
               "Interval: $($params.interval)",
               "Centered-messages:`n$($messages.message."centered-name")",
               "Sounds:",
               "  message1: []",
               "Messages:`n$($messages.message.message)",
               "World-messaging:",
               "  world: []" )

}
Add-Content -Path ".\config.yml" -value $document.start
Add-Content -Path ".\config.yml" -value $document.defaults